### ISSUE TITLE
Populate needed software for lab provisioning

### ISSUE THREAD

**Issue by phentos** [kevshin2002/thwebdev#8]
As a comment on this issue, please provide what software hackers will need already installed on their lab computers (if nothing is needed, state so).

**Comment by kevshin2002** [comment]
- Visual Studio Code
 - Python 3.7

Python Packages:
- FastAPI
- Uvicorn
- pydantic

Control:
Github Desktop (If teams want to use it) (not necessary)

**Comment by phentos** [comment]
Does the Python version matter (or either FastAPI or uvicorn)?

**Comment by kevshin2002** [comment]
Latest version of each software.

FastAPI and Uvicorn both require 3.7 to ensure full backward compatibility with whatever we're using.

Need to install pydantic as well which works with python 3.7.

**Comment by kevshin2002** [comment]
This did not show up in discord but pydantic also needs to be installed.

**Comment by phentos** [comment]
Submitted
